name: build
on:
  workflow_run:
    workflows:
      - lint
    branches:
      - main
    types:
      - completed

# TODO: Upload Test Coverage as Artifact、コメントアウトを解除。
# TODO: semantic-release、Netlify、Codecov、トークンを追加。
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_commit.message, 'Merge pull request')
    environment:
      name: production
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install npm
        run: |
          yarn --frozen-lockfile
      # deploy
      - name: Build a Project
        run: |
          npm run build
      - name: Create a Release
        run: |
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy to Production
        run: |
          echo 'Deploy to Production'
          npm run deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Create Coverage
        run: |
          echo 'Create Coverage'
          npm run ci:test:unit
      - name: Upload Test Coverage as Artifact
        # uses: actions/upload-artifact@v2
        # with:
        #   name: coverage
        #   path: coverage
        run: |
          echo 'Upload Test Coverage as Artifact'
      - name: Upload Test Coverage to Codecov
        run: |
          echo 'Upload Test Coverage to Codecov'
          # npm run ci:upload:coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
