name: issue
on:
  workflow_run:
    workflows:
      - build
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'failure' &&
      startsWith(github.event.workflow_run.head_commit.message, 'Merge pull request')
    steps:
      - name: Create Issue if the Workflows was Failed
        run: |
          echo "Create Issue"
          # TODO: ${{}} の中にスペース入れる
          # npm run ci:create:issue --workflow ${{github.event.repository.html_url}}/actions/runs/${{github.run_id}} --commit ${{github.event.repository.html_url}}/commits/${{github.sha}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
