name: lint
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
      - 'v*.*.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install npm
        run: |
          yarn --frozen-lockfile
      - name: Check Type
        run: |
          npm run ci:check:type
      - name: Check Code Format
        run: |
          npm run ci:check:format
      # lint-mince
      - name: Lint Config
        run: |
          echo 'Lint Config'
          # npm run ci:check:config
      - name: Lint Commit
        run: |
          echo 'Lint Commit'
          # npm run ci:check:commit
      - name: Lint Markdown
        run: |
          echo 'Lint Markdown'
          # npm run ci:check:md
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    environment:
      name: development
    steps:
      # install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install npm
        run: |
          yarn --frozen-lockfile
      - name: Create Env File
        run: |
          # FYI: https://teratail.com/questions/318264#reply-442858
          touch .env.development .env.production
          echo GATSBY_SITE_TITLE=${{ secrets.GATSBY_SITE_TITLE }} >> .env.development
          echo GATSBY_SITE_TITLE=${{ secrets.GATSBY_SITE_TITLE }} >> .env.production
          echo GATSBY_SITE_AUTHOR_NAME=${{ secrets.GATSBY_SITE_AUTHOR_NAME }} >> .env.development
          echo GATSBY_SITE_AUTHOR_NAME=${{ secrets.GATSBY_SITE_AUTHOR_NAME }} >> .env.production
          echo GATSBY_SITE_AUTHOR_SUMMARY=${{ secrets.GATSBY_SITE_AUTHOR_SUMMARY }} >> .env.development
          echo GATSBY_SITE_AUTHOR_SUMMARY=${{ secrets.GATSBY_SITE_AUTHOR_SUMMARY }} >> .env.production
          echo GATSBY_SITE_DESCRIPTION=${{ secrets.GATSBY_SITE_DESCRIPTION }} >> .env.development
          echo GATSBY_SITE_DESCRIPTION=${{ secrets.GATSBY_SITE_DESCRIPTION }} >> .env.production
          echo GATSBY_SITE_URL=${{ secrets.GATSBY_SITE_URL }} >> .env.development
          echo GATSBY_SITE_URL=${{ secrets.GATSBY_SITE_URL }} >> .env.production
          echo GATSBY_GITHUB_ACCOUNT=${{ secrets.GATSBY_GITHUB_ACCOUNT }} >> .env.development
          echo GATSBY_GITHUB_ACCOUNT=${{ secrets.GATSBY_GITHUB_ACCOUNT }} >> .env.production
          echo GATSBY_TWITTER_ACCOUNT=${{ secrets.GATSBY_TWITTER_ACCOUNT }} >> .env.development
          echo GATSBY_TWITTER_ACCOUNT=${{ secrets.GATSBY_TWITTER_ACCOUNT }} >> .env.production
          cat .env.development
      - name: Run Unit and Snapshot Test with Coverage
        run: |
          # TODO: Check Code Coverage
          echo 'Run Unit and Snapshot Test with Coverage'
          npm run ci:test:unit
      - name: Run Styleguide's Accessibility and Visual Regression Test
        run: |
          echo "Run Styleguide's Accessibility and Visual Regression Test"
          # FIXME: Docker 環境と CI 環境でレンダリング内容に差が出るため
          # npm run ci:test:styleguide
      - name: Run E2E and Snapshot Test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          command: |
            echo "Run E2E and Snapshot Test"
            # FIXME: Docker 環境と CI 環境でレンダリング内容に差が出るため
            # npm run ci:test:e2e
      - name: Run SEO Test
        run: |
          echo 'Run SEO Test'
          npm run ci:test:seo --slug=blog/sample/
